### ISSUE TITLE
Compilation error on newer linux kernel

### ISSUE THREAD

**Issue by mastrain** [D-TACQ/AFHBA404#103]
According to these changes:

https://github.com/torvalds/linux/commit/359745d78351c6f5442435f81549f0207ece28aa

Conflicts with 

https://github.com/D-TACQ/AFHBA404/blob/master/afs_procfs.c

PDE_DATA replaced with pde_data(); allowed to compile successfully again. I tested this with Rocky Linux 9.2 kernel rt5.14

**Comment by petermilne** [comment]
Thanks very much for the heads up. It's good to know.  Our problem with this source is that it has to compile with ALL known kernels, including a bunch of very old ones. We normally work around with a VERSION aware shim..

Please try this fix:
https://github.com/D-TACQ/AFHBA404/tree/issue103

https://github.com/D-TACQ/AFHBA404/commit/742f79e6b9758ef574afff2efffde2161816cb63
