### ISSUE TITLE
poll is not implemented for '/dev/rtm-t.?'

### ISSUE THREAD

**Issue by zack-vii** [D-TACQ/AFHBA404#42]
Hi there Peter,

Is there a way to use select on dma read.
Currently it seem select returns immediately claiming  /dev/rtm-t.? is readable but then blocks on read.
Is it possible to implements the poll function for dma read?

```c
        static int stop = eventfd(0, EFD_CLOEXEC | EFD_SEMAPHORE);
        ...
        RTM_T_Device *dev = new RTM_T_Device(0);
        const int fd = dev->getDeviceHandle();
        fd_set rfds;
        FD_ZERO(&rfds);
        FD_SET(fd, &rfds);
        FD_SET(stop, &rfds);
        const int maxfd = stop > fd ? stop : fd;
        const int sel = select(maxfd+1, &rfds, NULL, NULL, NULL);
        if (sel == -1)
        {
                perror("select error");
                return -1;
        }
        else if (sel)
        {
                if (FD_ISSET(fd, &rfds))
                {
                        const int nread = read(fd, sbd, SBDN*SBDSZ); // enter and blocks despite select
                        if (nread < 0)
                        {
                                stream->nbuf = 0;
                                perror("read error");
                                return -2;
                        }
                        else
                        {
                                return  nread/SBDSZ;
                        }
                }
                else
                {
                        return -7;
                }
        }
        else
        {
                fprintf(stderr, "timeout.\n");
                return -1;
        }
        ...
```

Cheers

Timo

**Comment by zack-vii** [comment]
```c
    struct pollfd pfds[2] = {{0}, {0}};
    pfds[0].fd = fd;
    pfds[1].fd = stop;
    pfds[0].events = pfds[1].events = POLLIN;
    const int ready = poll(pfds, 2, -1);
    # ready is 1
    # and pfds is {{fd = 4, events = 1, revents = 1}, {fd = 3, events = 1, revents = 0}}
```

**Comment by petermilne** [comment]
Hello Timo

Easily done ..

On 29/06/2020 19:15, Timo Schroeder wrote:
> ```c
>      struct pollfd pfds[2] = {{0}, {0}};
>      pfds[0].fd = fd;
>      pfds[1].fd = stop;
>      pfds[0].events = pfds[1].events = POLLIN;
>      const int ready = poll(pfds, 2, -1);
>      # ready is 1
>      # and pfds is {{fd = 4, events = 1, revents = 1}, {fd = 3, events = 1, revents = 0}}
> ```
> 
I don't recognise the above, but as a translation of something that's worked well for me before, the attached should work. It compiles, I'm hoping you'll test it ..

Cheers

Peter


dt100@seil AFHBA404]$ patch -p0 < afs_dma_poll.diff
patching file afhba_stream_drv.c
[dt100@seil AFHBA404]$ make
...
make -C /lib/modules/3.10.0-1062.1.2.el7.x86_64/build M=/home/dt100/PROJECTS/AFHBA404  modules
make[1]: Entering directory `/usr/src/kernels/3.10.0-1062.1.2.el7.x86_64'
   CC [M]  /home/dt100/PROJECTS/AFHBA404/afhba_stream_drv.o
   LD [M]  /home/dt100/PROJECTS/AFHBA404/afhba.o
   Building modules, stage 2.
   MODPOST 1 modules
   CC      /home/dt100/PROJECTS/AFHBA404/afhba.mod.o
   LD [M]  /home/dt100/PROJECTS/AFHBA404/afhba.ko


-- 
Peter Milne
Director of Sales
www.d-tacq.com

**Comment by zack-vii** [comment]
hm how do i get afs_dma_poll.diff, if you send it as attachment, github might have stripped it. did you push it as a branch?

**Comment by petermilne** [comment]
... or easier, just committed it:
To github.com:D-TACQ/AFHBA404.git
    d6f4dee..088c9dd  master -> master


On 29/06/2020 22:45, Timo Schroeder wrote:
> hm how do i get afs_dma_poll.diff, if you send it as attachment, github might have stripped it. did you push it as a branch?
> 
> 


-- 
Peter Milne
Director of Sales
www.d-tacq.com

**Comment by zack-vii** [comment]
this work. well the empy_list was what i was missing. i added some small improvements and will boil it down to a PR when i am done testing . thanks
